import React, { useState, useEffect } from 'react';
import { useApp } from '../../context/AppContext';
import { api } from '../../services/api';
import { Bill, Product } from '../../types';
import { formatINR } from '../../utils/currency';
import {
  Receipt,
  Plus,
  Trash2,
  Printer,
  CheckCircle2,
  User,
  Phone,
  QrCode,
  CreditCard,
  Building2,
  DollarSign,
  Search,
  Lock
} from 'lucide-react';

export const AdminBilling: React.FC = () => {
  const { activeAdminId, refreshDataFlag, triggerRefresh, addToast, setViewingInvoice } = useApp();
  const [bills, setBills] = useState<Bill[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [activeSubTab, setActiveSubTab] = useState<'history' | 'pos'>('history');

  // POS State
  const [customerName, setCustomerName] = useState('Walk-in Customer');
  const [customerPhone, setCustomerPhone] = useState('+1 (555) 987-6543');
  const [customerEmail, setCustomerEmail] = useState('walkin.customer@gmail.com');
  const [customerGstin, setCustomerGstin] = useState('');
  const [paymentMode, setPaymentMode] = useState<'Cash' | 'UPI' | 'Card' | 'Net Banking'>('Cash');

  // POS Items
  const [posCart, setPosCart] = useState<{ product: Product; quantity: number }[]>([]);
  const [selectedProductId, setSelectedProductId] = useState('');
  const [posDiscount, setPosDiscount] = useState(0);

  const fetchData = async () => {
    const [bList, pList] = await Promise.all([
      api.getBills(activeAdminId),
      api.getProducts({ admin_owner: activeAdminId })
    ]);
    setBills(bList);
    setProducts(pList);
    if (pList.length > 0 && !selectedProductId) setSelectedProductId(pList[0].product_id);
  };

  useEffect(() => {
    fetchData();
  }, [activeAdminId, refreshDataFlag]);

  const handleAddPosItem = () => {
    const targetProduct = products.find((p) => p.product_id === selectedProductId);
    if (!targetProduct) return;

    const existingIndex = posCart.findIndex((i) => i.product.product_id === selectedProductId);
    if (existingIndex > -1) {
      const updated = [...posCart];
      updated[existingIndex].quantity += 1;
      setPosCart(updated);
    } else {
      setPosCart([...posCart, { product: targetProduct, quantity: 1 }]);
    }
  };

  const handleUpdatePosQty = (prodId: string, qty: number) => {
    if (qty <= 0) {
      setPosCart(posCart.filter((i) => i.product.product_id !== prodId));
    } else {
      setPosCart(posCart.map((i) => (i.product.product_id === prodId ? { ...i, quantity: qty } : i)));
    }
  };

  const posSubtotal = posCart.reduce((sum, item) => sum + item.product.price * item.quantity, 0);
  const posTaxable = Math.max(0, posSubtotal - posDiscount);
  const posCgst = posTaxable * 0.09;
  const posSgst = posTaxable * 0.09;
  const posGrandTotal = posTaxable + posCgst + posSgst;

  const handleGeneratePosInvoice = async (e: React.FormEvent) => {
    e.preventDefault();
    if (posCart.length === 0) {
      addToast('Empty POS Cart', 'Please add at least one item to generate a bill.', 'error');
      return;
    }

    try {
      const billPayload = {
        admin_id: activeAdminId,
        customer_name: customerName,
        customer_phone: customerPhone,
        customer_email: customerEmail,
        customer_gstin: customerGstin,
        products: posCart.map((i) => ({
          product_id: i.product.product_id,
          product_name: i.product.product_name,
          price: i.product.price,
          quantity: i.quantity,
          discount: 0,
          gst_rate: 18
        })),
        subtotal: posSubtotal,
        discount_flat: posDiscount,
        payment_method: paymentMode,
        notes: 'Counter POS bill generated by admin'
      };

      const newBill = await api.createBill(billPayload);
      addToast('POS Bill Created', `Invoice ${newBill.invoice_number} generated successfully!`);

      // Reset POS cart & open invoice view!
      setPosCart([]);
      setViewingInvoice(newBill);
      triggerRefresh();
      setActiveSubTab('history');
    } catch (err: any) {
      addToast('POS Error', err.message, 'error');
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Navigation Sub-Tabs */}
      <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-4">
        <div>
          <h1 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight">
            Vyapar Billing & Counter POS Engine
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Offline store bill creation, automated 18% GST tax calculation, & invoice archives
          </p>
        </div>

        <div className="flex bg-slate-100 dark:bg-slate-800 p-1 rounded-2xl text-xs font-semibold">
          <button
            onClick={() => setActiveSubTab('history')}
            className={`px-4 py-2 rounded-xl transition ${activeSubTab === 'history' ? 'bg-indigo-600 text-white shadow' : 'text-slate-600 dark:text-slate-300'}`}
          >
            Invoice Archives ({bills.length})
          </button>
          <button
            onClick={() => setActiveSubTab('pos')}
            className={`px-4 py-2 rounded-xl transition flex items-center gap-1.5 ${activeSubTab === 'pos' ? 'bg-emerald-600 text-white shadow' : 'text-slate-600 dark:text-slate-300'}`}
          >
            <Plus className="w-3.5 h-3.5" /> New Counter POS Bill
          </button>
        </div>
      </div>

      {activeSubTab === 'history' ? (
        /* History View */
        <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50 text-slate-400 uppercase font-extrabold text-[10px]">
                  <th className="py-3 px-4">Invoice #</th>
                  <th className="py-3 px-4">Customer Name</th>
                  <th className="py-3 px-4">Date</th>
                  <th className="py-3 px-4">Payment</th>
                  <th className="py-3 px-4">Tax (CGST+SGST)</th>
                  <th className="py-3 px-4">Grand Total</th>
                  <th className="py-3 px-4 text-right">View / Print PDF</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                {bills.map((b) => (
                  <tr key={b.bill_id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50">
                    <td className="py-3.5 px-4 font-mono font-bold text-indigo-600 dark:text-indigo-400">
                      {b.invoice_number}
                    </td>

                    <td className="py-3.5 px-4">
                      <span className="font-bold text-slate-900 dark:text-white block">{b.customer_name}</span>
                      <span className="text-[10px] text-slate-400">{b.customer_phone}</span>
                    </td>

                    <td className="py-3.5 px-4 font-mono text-slate-500">{b.created_at}</td>

                    <td className="py-3.5 px-4">
                      <span className="px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 font-bold text-[10px]">
                        {b.payment_mode}
                      </span>
                    </td>

                    <td className="py-3.5 px-4 font-mono text-slate-500">
                      {formatINR(((b.cgst ?? 0) + (b.sgst ?? 0)))}
                    </td>

                    <td className="py-3.5 px-4 font-mono font-bold text-slate-900 dark:text-white text-sm">
                      {formatINR((b.grand_total ?? 0))}
                    </td>

                    <td className="py-3.5 px-4 text-right">
                      <button
                        onClick={() => setViewingInvoice(b)}
                        className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl text-xs shadow transition inline-flex items-center gap-1"
                      >
                        <Receipt className="w-3.5 h-3.5" /> View Invoice
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        /* Counter POS Terminal Form */
        <form onSubmit={handleGeneratePosInvoice} className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Customer & Payment Form */}
          <div className="p-6 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm space-y-4 text-xs">
            <h3 className="font-extrabold text-slate-900 dark:text-white text-base border-b pb-2">
              1. Customer Information
            </h3>

            <div>
              <label className="block font-semibold text-slate-700 dark:text-slate-300 mb-1">Customer Name</label>
              <input
                type="text"
                required
                value={customerName}
                onChange={(e) => setCustomerName(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-slate-300 bg-white text-slate-900 placeholder:text-slate-400 dark:bg-slate-800 dark:border-slate-700 dark:text-slate-100 dark:placeholder:text-slate-500"
              />
            </div>

            <div>
              <label className="block font-semibold text-slate-700 dark:text-slate-300 mb-1">Phone Number</label>
              <input
                type="text"
                required
                value={customerPhone}
                onChange={(e) => setCustomerPhone(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-slate-300 bg-white text-slate-900 placeholder:text-slate-400 dark:bg-slate-800 dark:border-slate-700 dark:text-slate-100 dark:placeholder:text-slate-500"
              />
            </div>

            <div>
              <label className="block font-semibold text-slate-700 dark:text-slate-300 mb-1">Email Address</label>
              <input
                type="email"
                required
                value={customerEmail}
                onChange={(e) => setCustomerEmail(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-slate-300 bg-white text-slate-900 placeholder:text-slate-400 dark:bg-slate-800 dark:border-slate-700 dark:text-slate-100 dark:placeholder:text-slate-500"
              />
            </div>

            <div>
              <label className="block font-semibold text-slate-700 dark:text-slate-300 mb-1">
                Customer GSTIN (Optional B2B)
              </label>
              <input
                type="text"
                value={customerGstin}
                onChange={(e) => setCustomerGstin(e.target.value)}
                placeholder="27ABCDE1234F1Z5"
                className="w-full px-3 py-2 rounded-xl border border-slate-300 bg-white text-slate-900 placeholder:text-slate-400 dark:bg-slate-800 dark:border-slate-700 dark:text-slate-100 dark:placeholder:text-slate-500 font-mono uppercase"
              />
            </div>

            <h3 className="font-extrabold text-slate-900 dark:text-white text-base border-b pt-2 pb-2">
              2. Payment Mode
            </h3>

            <div className="grid grid-cols-2 gap-2">
              {(['Cash', 'UPI', 'Card', 'Net Banking'] as const).map((m) => (
                <button
                  key={m}
                  type="button"
                  onClick={() => setPaymentMode(m)}
                  className={`p-2.5 rounded-xl border text-center font-bold transition ${paymentMode === m ? 'bg-indigo-600 text-white border-indigo-600 shadow' : 'bg-slate-50 dark:bg-slate-800 text-slate-700 dark:text-slate-300'}`}
                >
                  {m}
                </button>
              ))}
            </div>
          </div>

          {/* POS Item Picker & Billing Basket */}
          <div className="lg:col-span-2 p-6 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm space-y-4 text-xs">
            <h3 className="font-extrabold text-slate-900 dark:text-white text-base border-b pb-2">
              3. Select Products & Quantities
            </h3>

            <div className="flex gap-2">
              <select
                value={selectedProductId}
                onChange={(e) => setSelectedProductId(e.target.value)}
                className="flex-1 px-3 py-2 rounded-xl border border-slate-300 bg-slate-50 text-slate-900 font-semibold text-xs dark:bg-slate-800 dark:border-slate-700 dark:text-slate-100"
              >
                {products.map((p) => (
                  <option key={p.product_id} value={p.product_id}>
                    {p.product_name} - {formatINR(p.price)} (In Stock: {p.stock})
                  </option>
                ))}
              </select>

              <button
                type="button"
                onClick={handleAddPosItem}
                className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl shadow flex items-center gap-1"
              >
                <Plus className="w-4 h-4" /> Add to POS Bill
              </button>
            </div>

            {/* Cart Table */}
            <div className="border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-50 dark:bg-slate-800/50 border-b text-slate-400 font-extrabold text-[10px]">
                    <th className="p-2.5">Product</th>
                    <th className="p-2.5">Price</th>
                    <th className="p-2.5">Qty</th>
                    <th className="p-2.5">Total</th>
                    <th className="p-2.5 text-right">Remove</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {posCart.length === 0 ? (
                    <tr>
                      <td colSpan={5} className="p-6 text-center text-slate-400">
                        No items added to counter bill yet.
                      </td>
                    </tr>
                  ) : (
                    posCart.map((item) => (
                      <tr key={item.product.product_id}>
                        <td className="p-2.5 font-bold text-slate-900 dark:text-white">{item.product.product_name}</td>
                        <td className="p-2.5 font-mono">{formatINR(item.product.price)}</td>
                        <td className="p-2.5">
                          <input
                            type="number"
                            min="1"
                            value={item.quantity}
                            onChange={(e) => handleUpdatePosQty(item.product.product_id, Number(e.target.value))}
                            className="w-14 px-2 py-1 rounded border border-slate-300 bg-slate-50 text-slate-900 font-mono font-bold dark:bg-slate-800 dark:border-slate-700 dark:text-slate-100"
                          />
                        </td>
                        <td className="p-2.5 font-mono font-bold text-slate-900 dark:text-white">
                          {formatINR((item.product?.price ?? 0) * item.quantity)}
                        </td>
                        <td className="p-2.5 text-right">
                          <button
                            type="button"
                            onClick={() => handleUpdatePosQty(item.product.product_id, 0)}
                            className="text-rose-500 hover:text-rose-700"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            {/* POS Calculation Box */}
            <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-200 dark:border-slate-800 space-y-1.5 font-mono">
              <div className="flex justify-between text-slate-600 dark:text-slate-400">
                <span>Subtotal Amount:</span>
                <span>{formatINR(posSubtotal ?? 0)}</span>
              </div>

              <div className="flex justify-between items-center text-slate-600 dark:text-slate-400">
                <span>Custom Counter Discount (₹):</span>
                <input
                  type="number"
                  min="0"
                  value={posDiscount}
                  onChange={(e) => setPosDiscount(Number(e.target.value))}
                  className="w-20 px-2 py-0.5 rounded border border-slate-300 bg-slate-50 text-slate-900 text-right font-mono dark:bg-slate-800 dark:border-slate-700 dark:text-slate-100"
                />
              </div>

              <div className="flex justify-between text-slate-600 dark:text-slate-400">
                <span>CGST Tax (9%):</span>
                <span>+{formatINR(posCgst ?? 0)}</span>
              </div>

              <div className="flex justify-between text-slate-600 dark:text-slate-400">
                <span>SGST Tax (9%):</span>
                <span>+{formatINR(posSgst ?? 0)}</span>
              </div>

              <div className="flex justify-between text-base font-extrabold text-slate-900 dark:text-white border-t pt-2">
                <span>Grand Total Payable:</span>
                <span className="text-emerald-600 dark:text-emerald-400">{formatINR(posGrandTotal ?? 0)}</span>
              </div>
            </div>

            <button
              type="submit"
              disabled={posCart.length === 0}
              className="w-full py-3.5 bg-emerald-600 hover:bg-emerald-700 disabled:bg-slate-300 text-white font-bold rounded-xl shadow-lg transition flex items-center justify-center gap-2 text-xs"
            >
              <Printer className="w-4 h-4" /> Generate & Print Official Vyapar Invoice
            </button>
          </div>
        </form>
      )}
    </div>
  );
};
